### ISSUE TITLE
Use snackbar instead of toasts for feedback messages.

### ISSUE THREAD

**Issue by ayush0402** [ayush0402/tic-tac-toe-foss#1]
Currently, the app uses `toasts` for feedback messages to the user for example, when clicked on `PLAY WITH COMPUTER` button.

We want to replace this by `snackbars` instead of toasts for having a better looking material UI.

Take references from stackoverflow and [Android developers guide](https://developer.android.com/reference/com/google/android/material/snackbar/Snackbar).

**Comment by Animeshz** [comment]
I'd like to work on this!

**Comment by Rohit1173** [comment]
Assigned it to you @Animeshz , now you can work on
