### ISSUE TITLE
Missing Content Description for ImageButtons in the 3rd Row in activity_menu.xml

### ISSUE THREAD

**Issue by Rohit1173** [ayush0402/tic-tac-toe-foss#12]
Set a Content Description for the ImageButton in the 3rd row for the 3x3 grid (i.e., btn7, btn8, btn9), and don't forget to use the `@string` resource while writing the Content Description

**Comment by TsarPrince** [comment]
Sir please assign me this

**Comment by Rohit1173** [comment]
Assigned!
