### ISSUE TITLE
Removing unused imports in menu.kt

### ISSUE THREAD

**Issue by Rohit1173** [ayush0402/tic-tac-toe-foss#18]
There were a few unused imports in the menu.kt, Remove them

**Comment by TsarPrince** [comment]
Sir I would like to fix this. Please assign it to me.

**Comment by Rohit1173** [comment]
Assigned!

**Comment by TsarPrince** [comment]
@Rohit1173 sir, there are unused imports in MainActivity.kt also, they should also be removed?

**Comment by Rohit1173** [comment]
> @Rohit1173 sir, there are unused imports in MainActivity.kt also, they should also be removed?

Don't remove them it would be helpful for others to work on it as an issue
