### ISSUE TITLE
Adjusting size of the Button in activity_main.xml

### ISSUE THREAD

**Issue by Rohit1173** [ayush0402/tic-tac-toe-foss#19]
* The text `Play With Human` in `btnplaywithhuman` Button has trailing and leading white spaces So that it matches the width of the button below (i.e.,btnplaywithcomp)
* Remove the trailing and leading white spaces for that text and make some UI changes for that button So that it should look the same as before

**Comment by Perumallpardhiv** [comment]
Sir can I solve on this issue ?

**Comment by Rohit1173** [comment]
Assigned
