### ISSUE TITLE
Implement view binding in the project to access views easily replacing redundant findViewById function.

### ISSUE THREAD

**Issue by ayush0402** [ayush0402/tic-tac-toe-foss#2]
Currently all views in the project are being referenced into the Kotlin files using `findViewById` method. 

We want to enable view binding at all places so that views can be directly accessed using `binding.<view_id>` instead.

Reference: https://developer.android.com/topic/libraries/view-binding

**Comment by Animeshz** [comment]
I think I can work on it, can you please assign it to me?
