### ISSUE TITLE
Missing Content Description for ImageButton in activity_menu.xml

### ISSUE THREAD

**Issue by Rohit1173** [ayush0402/tic-tac-toe-foss#9]
Set a Content Description for the ImageButton(GitHub icon) and don't forget to use the `@string` resource while writing the Content Description

**Comment by Perumallpardhiv** [comment]
Sir I will try this could u assign .

**Comment by Rohit1173** [comment]
@Perumallpardhiv as you had completed 3 PR's in this repo, we recommend you to work on [this](https://github.com/Rohit1173/TODO-APP-FOSS) repo

**Comment by Perumallpardhiv** [comment]
@Rohit1173 sir Ok sir👍

**Comment by superiorsd10** [comment]
@Rohit1173 Sir, I think I acquire enough knowledge to resolve this issue, so please consider assigning it to me.

**Comment by Rohit1173** [comment]
Assigned!
